modLoader = "javafml"
loaderVersion = "[41,)"
license = "${license_name}"
issueTrackerURL = "${github_url}/issues"
showAsResourcePack = false

[[mods]]
modId = "homecamp"
version = "${version}"
displayName = "${readable_name}"
updateJSONURL = "${forge_update_json_url}"
displayURL = "${forge_curseforge_url}"
logoFile = "${logo_filename}"
credits = ""
authors = "The_Fireplace"
description = "${mod_description}"

[[dependencies.homecamp]]
modId = "forge"
mandatory = true
versionRange = "[41,41.0.94)"
ordering = "NONE"
side = "BOTH"

[[dependencies.homecamp]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.homecamp]]
modId = "annotateddi"
mandatory = true
versionRange = "[4,5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.homecamp]]
modId = "fireplacelib"
mandatory = true
versionRange = "[7,8)"
ordering = "NONE"
side = "BOTH"